[package]
name = "libu"
version = "1.0.0"
edition = "2024"
authors = ["RunThem <iccy.fun@outlook.com>"]
license = "MIT"
description = "Utils library."
repository = "https://github.com/RunThem/libu.rs"

[workspace]
members = ["libu-builder", "libu-urc"]
resolver = "2"

[dependencies]
libu-urc = { path = "libu-urc" }
libu-builder = { path = "libu-builder" }

itertools = "0.14.0"
bytes = "1.10.1"
