[package]
name = "libu"
version = "1.0.0"
edition = "2024"
authors = ["RunThem <iccy.fun@outlook.com>"]
license = "MIT"
description = "Utils library."
repository = "https://github.com/RunThem/libu.rs"

[workspace]
members = [
    "libu-derive",
    "libu-point",
    "libu-chan",
    "libu-macro",
    "libu-trait"
]

[workspace.dependencies]
parking_lot = "0.12.5"
flume = { version = "0.12.0", default-features = false, features = ['select'] }
extend = "1.2.0"
darling = "0.23.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full", "parsing", "printing", "extra-traits", "proc-macro", "derive", "clone-impls"] }
trybuild = "1.0.120"

[dependencies.parking_lot]
workspace = true

[dependencies.flume]
workspace = true

[dependencies.libu-chan]
path = "libu-chan"

[dependencies.libu-point]
path = "libu-point"

[dependencies.libu-derive]
path = "libu-derive"

[dependencies.libu-trait]
path = "libu-trait"

[dependencies.libu-macro]
path = "libu-macro"
